const bp = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

export const ARTIST = {
  name: "Bruno Beltrami",
  handle: "@bruno.belt",
  instagram: "https://www.instagram.com/bruno.belt",
  whatsapp: "5548998663124",
  location: "Santa Catarina — Brasil",
  portrait: `${bp}/artist/bruno.jpg`,
};

export const portfolioItems = [
  {
    id: 1,
    src: `${bp}/portfolio/victory.jpg`,
    alt: "Victory — deusa clássica em microrealismo com geometria orbital na mão",
    style: "Neo-Clássico",
    placement: "Mão",
    size: "large",
    label: "VICTORY",
  },
  {
    id: 2,
    src: `${bp}/portfolio/fortis-fortuna.jpg`,
    alt: "Fortis Fortuna Adiuvat — peito e braço com traços técnicos e sol geométrico",
    style: "Neo-Geométrico",
    placement: "Peito & Braço",
    size: "large",
    label: "FORTIS FORTUNA",
  },
  {
    id: 3,
    src: `${bp}/portfolio/destiny.jpg`,
    alt: "Destiny — astronauta, cervo e geometria cósmica em manga fechada",
    style: "Collage",
    placement: "Braço",
    size: "large",
    label: "DESTINY",
  },
  {
    id: 4,
    src: `${bp}/portfolio/memento-mori.jpg`,
    alt: "Memento Mori — Ícaro em ascensão com águia e geometria no antebraço",
    style: "Neo-Clássico",
    placement: "Antebraço",
    size: "medium",
    label: "MEMENTO MORI",
  },
  {
    id: 5,
    src: `${bp}/portfolio/navigator.jpg`,
    alt: "Navigator — guerreiro romano com bússola e cartografia no ombro",
    style: "Neo-Clássico",
    placement: "Ombro",
    size: "medium",
    label: "NAVIGATOR",
  },
  {
    id: 6,
    src: `${bp}/portfolio/sapientia.jpg`,
    alt: "Sapientia et Fides — monge e anjo em narrativa visual nas costas",
    style: "Neo-Clássico",
    placement: "Costas",
    size: "large",
    label: "SAPIENTIA",
  },
  {
    id: 7,
    src: `${bp}/portfolio/psyche.jpg`,
    alt: "Psyché — rosto em microrealismo com geometria radiante no ombro",
    style: "Neo-Geométrico",
    placement: "Ombro",
    size: "medium",
    label: "PSYCHÉ",
  },
  {
    id: 8,
    src: `${bp}/portfolio/gloria.jpg`,
    alt: "Gloria — anjo guerreiro com espada e geometria celeste no antebraço",
    style: "Neo-Clássico",
    placement: "Antebraço",
    size: "medium",
    label: "GLORIA",
  },
  {
    id: 9,
    src: `${bp}/portfolio/fides.jpg`,
    alt: "Fides — composição com cruz, figuras e sistema planetário no braço",
    style: "Collage",
    placement: "Braço",
    size: "small",
    label: "FIDES",
  },
];

export const flashItems = [
  {
    id: "flash-01",
    name: "Filósofo no Trono",
    style: "Neo-Clássico",
    description: "Figura entronada com leões, geometria sagrada, candlesticks e elmo espartano com flecha. Composição monumental.",
    src: `${bp}/flashes/filosofo-trono.jpg`,
    simSrc: `${bp}/flashes/sim/filosofo-trono.png`,
    placeholder: "⚖️",
  },
  {
    id: "flash-02",
    name: "Mente Aberta",
    style: "Surrealismo",
    description: "Perfil feminino com cérebro exposto, sistema vascular, coração anatômico e olho em mandala geométrica.",
    src: `${bp}/flashes/mente-aberta.jpg`,
    simSrc: `${bp}/flashes/sim/mente-aberta.png`,
    placeholder: "🧠",
  },
  {
    id: "flash-03",
    name: "Ad Astra",
    style: "Collage",
    description: "Astronauta com ônibus espacial, bonsai e rosto fraturado — do cosmos ao humano. Ideal para manga.",
    src: `${bp}/flashes/ad-astra.jpg`,
    simSrc: `${bp}/flashes/sim/ad-astra.png`,
    placeholder: "🚀",
  },
  {
    id: "flash-04",
    name: "Veni Vidi Vici",
    style: "Neo-Clássico",
    description: "Busto romano em colagem com texto clássico — escultura greco-romana e tipografia monumental.",
    src: `${bp}/flashes/veni-vidi-vici.jpg`,
    simSrc: `${bp}/flashes/sim/veni-vidi-vici.png`,
    placeholder: "🏛️",
  },
  {
    id: "flash-05",
    name: "Imperator",
    style: "Neo-Clássico",
    description: "Águia em voo sobre busto de guerreiro romano com bússola geométrica — liberdade, poder e precisão.",
    src: `${bp}/flashes/imperator.jpg`,
    simSrc: `${bp}/flashes/sim/imperator.png`,
    placeholder: "🦅",
  },
  {
    id: "flash-06",
    name: "Coruja Maçônica",
    style: "Neo-Geométrico",
    description: "Coruja em voo com coluna jônica, símbolo maçônico e traços arquitetônicos. Conhecimento e mistério.",
    src: `${bp}/flashes/coruja-maconica.jpg`,
    simSrc: `${bp}/flashes/sim/coruja-maconica.png`,
    placeholder: "🦉",
  },
  {
    id: "flash-07",
    name: "Águia Courage",
    style: "Neo-Geométrico",
    description: "Águia em microrealismo com geometria cósmica, elipses e tipografia vertical COURAGE.",
    src: `${bp}/flashes/aguia-courage.jpg`,
    simSrc: `${bp}/flashes/sim/aguia-courage.png`,
    placeholder: "⚡",
  },
  {
    id: "flash-08",
    name: "Rosa e Mão",
    style: "Collage",
    description: "Mão segurando rosa em colagem surrealista com olho e elementos fragmentados. Beleza e fragilidade.",
    src: `${bp}/flashes/rosa-mao.jpg`,
    simSrc: `${bp}/flashes/sim/rosa-mao.png`,
    placeholder: "🌹",
  },
];
