export const ARTIST = {
  name: "Bruno Beltrami",
  handle: "@bruno.belt",
  instagram: "https://www.instagram.com/bruno.belt",
  whatsapp: "5548998663124",
  location: "Santa Catarina — Brasil",
};

export const portfolioItems = [
  {
    id: 1,
    src: "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=800&q=90",
    alt: "Memento Mori — figura greco-romana em ascensão com geometria sagrada",
    style: "Neo-Clássico",
    placement: "Antebraço",
    size: "large",
    label: "MEMENTO MORI",
  },
  {
    id: 2,
    src: "https://images.unsplash.com/photo-1542382943-3ac575b0c48d?w=800&q=90",
    alt: "Fortis Fortuna Adiuvat — guerreiro espartano com traços técnicos e geometria",
    style: "Neo-Geométrico",
    placement: "Braço e Peito",
    size: "large",
    label: "FORTIS FORTUNA ADIUVAT",
  },
  {
    id: 3,
    src: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=800&q=90",
    alt: "Carpe Diem — face com geometria radiante e fases da lua",
    style: "Neo-Geométrico",
    placement: "Ombro",
    size: "medium",
    label: "CARPE DIEM",
  },
  {
    id: 4,
    src: "https://images.unsplash.com/photo-1590246814883-57c511e16514?w=800&q=90",
    alt: "Sapientia et Fides — figuras clássicas em colagem com moldura geométrica",
    style: "Neo-Clássico",
    placement: "Costas",
    size: "large",
    label: "SAPIENTIA ET FIDES",
  },
  {
    id: 5,
    src: "https://images.unsplash.com/photo-1607083205523-7e05b7eb6a0c?w=800&q=90",
    alt: "Destiny — astronauta com geometria cósmica e cervo realista",
    style: "Collage",
    placement: "Braço",
    size: "small",
    label: "DESTINY",
  },
  {
    id: 6,
    src: "https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=800&q=90",
    alt: "Victory — rosto clássico em microrealismo com órbitas e pontuação geométrica",
    style: "Neo-Geométrico",
    placement: "Mão",
    size: "medium",
    label: "VICTORY",
  },
];

export const flashItems = [
  {
    id: "flash-01",
    name: "Rosa e Mão",
    style: "Collage",
    description: "Mão segurando rosa com elementos surrealistas e olhos ocultos",
    src: "/flashes/rosa-mao.svg",
    placeholder: "🌹",
  },
  {
    id: "flash-02",
    name: "Águia Courage",
    style: "Neo-Geométrico",
    description: "Águia realista com estrutura geométrica e tipografia COURAGE",
    src: "/flashes/aguia-courage.svg",
    placeholder: "🦅",
  },
  {
    id: "flash-03",
    name: "Coruja Maçônica",
    style: "Neo-Geométrico",
    description: "Coruja em voo com coluna jônica e símbolos maçônicos",
    src: "/flashes/coruja-maconica.svg",
    placeholder: "🦉",
  },
  {
    id: "flash-04",
    name: "Guerreiro e Águia",
    style: "Neo-Clássico",
    description: "Busto de guerreiro romano com águia em colagem geométrica",
    src: "/flashes/guerreiro-aguia.svg",
    placeholder: "⚔️",
  },
  {
    id: "flash-05",
    name: "Veni Vidi Vici",
    style: "Neo-Clássico",
    description: "Estatua romana do guerreiro com tipografia clássica e geometria",
    src: "/flashes/veni-vidi-vici.svg",
    placeholder: "🏛️",
  },
];
