export const portfolioItems = [
  {
    id: 1,
    src: "https://images.unsplash.com/photo-1565058379802-bbe93b2f703a?w=800&q=90",
    alt: "Tatuagem geométrica minimalista",
    style: "Fineline",
    placement: "Antebraço",
    size: "medium",
  },
  {
    id: 2,
    src: "https://images.unsplash.com/photo-1590246814883-57c511e16514?w=800&q=90",
    alt: "Blackwork floral",
    style: "Blackwork",
    placement: "Costela",
    size: "large",
  },
  {
    id: 3,
    src: "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=800&q=90",
    alt: "Tatuagem de cobra ornamental",
    style: "Ornamental",
    placement: "Perna",
    size: "small",
  },
  {
    id: 4,
    src: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=800&q=90",
    alt: "Mandala fineline",
    style: "Fineline",
    placement: "Costas",
    size: "large",
  },
  {
    id: 5,
    src: "https://images.unsplash.com/photo-1607083205523-7e05b7eb6a0c?w=800&q=90",
    alt: "Floral delicado",
    style: "Fineline",
    placement: "Tornozelo",
    size: "small",
  },
  {
    id: 6,
    src: "https://images.unsplash.com/photo-1542382943-3ac575b0c48d?w=800&q=90",
    alt: "Tribal moderno",
    style: "Blackwork",
    placement: "Ombro",
    size: "medium",
  },
];

export const flashItems = [
  {
    id: "flash-01",
    name: "Serpente Ornamental",
    style: "Blackwork",
    src: "/flashes/snake.png",
    placeholder: "🐍",
  },
  {
    id: "flash-02",
    name: "Rosa Fineline",
    style: "Fineline",
    src: "/flashes/rose.png",
    placeholder: "🌹",
  },
  {
    id: "flash-03",
    name: "Olho Sagrado",
    style: "Ornamental",
    src: "/flashes/eye.png",
    placeholder: "👁",
  },
  {
    id: "flash-04",
    name: "Lua e Estrelas",
    style: "Fineline",
    src: "/flashes/moon.png",
    placeholder: "🌙",
  },
  {
    id: "flash-05",
    name: "Borboleta Geométrica",
    style: "Geometric",
    src: "/flashes/butterfly.png",
    placeholder: "🦋",
  },
  {
    id: "flash-06",
    name: "Caveira Ornamental",
    style: "Blackwork",
    src: "/flashes/skull.png",
    placeholder: "💀",
  },
];
